- name: install cron job (ansible-pull)
  cron:
    user: aliesesay
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/aliesesay/ansible_works.git > /dev/null"
